#pragma once

#define IDR_COMBAT_POWER_PANEL_SKIN 301
#define IDR_COMBAT_RANK_EXPLORE 302
#define IDR_COMBAT_RANK_PIONEER 303
#define IDR_COMBAT_RANK_FEARLESS 304
#define IDR_COMBAT_RANK_CONQUER 305
#define IDR_COMBAT_RANK_BATTLE 306
#define IDR_COMBAT_RANK_HEROIC 307
#define IDR_COMBAT_RANK_MASTERY 308
#define IDR_COMBAT_RANK_TOOLTIP 309
