[Plugins]
Plugin0=PreventMinimize.dll
Plugin1=GameNative.dll
Plugin2=AutoFire.dll
Plugin3=EquipmentSwap.dll
Plugin4=DpsMeter.dll
Plugin5=CombatPower.dll
Plugin6=ImeFix.dll

[Debug]
; 打开后会在客户端目录写入 GameLog.log 和 CipherPacket.log
Enabled=1
